AMQP_URI: amqp://user:password@localhost:5672/
DB_URIS:
  'service_usuario:Base': 'mysql+pymysql://admin:admin@localhost:3306/abcBolinhas?charset=utf8'
rpc_exchange: 'nameko-rpc'
max_workers: 10
parent_calls_tracked: 10
